### ISSUE TITLE
prep for shiny future

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/wg-async-foundations#116]
We are going to start accepting shiny future stories! We need to do some prep work:

* [ ] update the [main "How to Vision" page](https://github.com/rust-lang/wg-async-foundations/blob/master/src/vision/how_to_vision.md) to mark that "shiny future pages" are being accepted
* [ ] update the [main "How to Shiny Future" page](https://github.com/rust-lang/wg-async-foundations/blob/master/src/vision/how_to_vision/shiny_future.md) to mark that "shiny future pages" are being accepted
* [ ] update the [shiny future](https://github.com/rust-lang/wg-async-foundations/blob/master/src/vision/shiny_future.md) page to direct to [have a section like this](https://github.com/rust-lang/wg-async-foundations/blob/master/src/vision/status_quo.md#-under-construction-help-needed-)
* [ ] update the [shiny future template](https://github.com/rust-lang/wg-async-foundations/blob/master/src/vision/shiny_future/template.md#-not-time-for-this-yet-) to not say that we are not accepting such stories
* [ ] create a github issue template similar to the [one for status quo issues](https://github.com/rust-lang/wg-async-foundations/blob/master/.github/ISSUE_TEMPLATE/-status-quo--story-issue.md)
