### ISSUE TITLE
Roadmap goal: Async fn everywhere

### ISSUE THREAD

**Issue by tmandry** [rust-lang/wg-async-foundations#242]
This issue tracks the steps for setting up a new top-level goal in the async vision [roadmap].
Please read the [instructions for owning a goal][owning].

Goal owner: @tmandry 

- [ ] Goal has a landing page listing the impact
- [ ] Initiatives are defined
- [ ] All initiatives have a landing page
    
    - [ ] 
- [ ] Goal and all initiatives listed on the [roadmap] with links to landing pages

Remember, you don't have to do these all at once!

This issue can be closed when all of the above items are complete.

[roadmap]: https://rust-lang.github.io/wg-async-foundations/vision/roadmap.html
[owning]: https://rust-lang.github.io/wg-async-foundations/vision/how_to_vision/owners.html
