### ISSUE TITLE
Roadmap initiative: async fundamentals

### ISSUE THREAD

**Issue by tmandry** [rust-lang/wg-async-foundations#243]
This issue tracks the steps for setting up a new initiative in the async vision [roadmap].
Please read the [instructions for owning an initiative][owning].

Top-level goal: #242 Async fn everywhere
Initiative owner: @tmandry 

Each initiative should have a landing page, linked to from the [roadmap]. This can be a page on this website or a dedicated repo.

For in-progress initiatives the landing page should include, or have pointers to:

- [ ] Goals and impact of the initiative
- [ ] Milestones
- [ ] Design notes and documentation (this may be sparse in the beginning)
- [ ] Links to any organizing tools, such as a project board
- [ ] The initiative owner
- [ ] The current set of [stakeholders] and the area(s) they represent
- [ ] Notes on how to get involved
- [ ] For landing pages not on this website, a link back to the overall [roadmap]

For making a dedicated repo, it's recommended to use this [initiative template][template] as a starting point.

Remember, you don't have to do these all at once!

This issue can be closed when all of the above items are complete.

[roadmap]: https://rust-lang.github.io/wg-async-foundations/vision/roadmap.html
[owning]: https://rust-lang.github.io/wg-async-foundations/vision/how_to_vision/owners.html
[stakeholders]: https://rust-lang.github.io/wg-async-foundations/vision/how_to_vision/stakeholders.html
[template]: https://github.com/rust-lang/initiative-template
