### ISSUE TITLE
Roadmap initiative: Sync and async code behaves the same

### ISSUE THREAD

**Issue by eholk** [rust-lang/wg-async-foundations#250]
This issue tracks the steps for setting up a new initiative in the async vision [roadmap].
Please read the [instructions for owning an initiative][owning].

Top-level goal: Polish (#249)
Initiative owner: Open

Each initiative should have a landing page, linked to from the [roadmap]. This can be a page on this website or a dedicated repo.

For in-progress initiatives the landing page should include, or have pointers to:

- [ ] Goals and impact of the initiative
- [ ] Milestones
- [ ] Design notes and documentation (this may be sparse in the beginning)
- [ ] Links to any organizing tools, such as a project board
- [ ] The initiative owner
- [ ] The current set of [stakeholders] and the area(s) they represent
- [ ] Notes on how to get involved
- [ ] For landing pages not on this website, a link back to the overall [roadmap]

For making a dedicated repo, it's recommended to use this [initiative template][template] as a starting point.

Remember, you don't have to do these all at once!

This issue can be closed when all of the above items are complete.

[roadmap]: https://rust-lang.github.io/wg-async-foundations/vision/roadmap.html
[owning]: https://rust-lang.github.io/wg-async-foundations/vision/how_to_vision/owners.html
[stakeholders]: https://rust-lang.github.io/wg-async-foundations/vision/how_to_vision/stakeholders.html
[template]: https://github.com/rust-lang/initiative-template

**Comment by eholk** [comment]
This came up in one of the planning meetings recently. It was @estebank that [suggested this](https://rust-lang.zulipchat.com/#narrow/stream/187312-wg-async-foundations/topic/sprint.20planning.202021-09-16/near/253609719). This initiative is not currently being worked on, but I thought it'd be good to capture some ideas in the meantime.

We'll need to be precise about what we mean by "behaves the same." Obviously async code will have different semantics, but I think the property we want is something like if you have a sync `fn` or a block, sticking the `async` keyword in front of it doesn't change the behavior unexpectedly. The error messages should be essentially the same (the async version may have something about the implicit future that's created), and if the code evaluates to a value, it should be the same one.

@nikomatsakis [had the idea](https://rust-lang.zulipchat.com/#narrow/stream/187312-wg-async-foundations/topic/sprint.20planning.202021-09-16/near/253610383) that we might be able to do something like fuzz testing, where we can automatically generate sync and async versions of the same program.

I think this initiative would be about defining what we mean by having the same behavior for sync and async, and then writing the program generator to build test cases.
