### ISSUE TITLE
[meta] Covering the full range of status-quo stories

### ISSUE THREAD

**Issue by eminence** [rust-lang/wg-async-foundations#98]
We want to make sure that we have stories that cover the full range experiences.  This list is not yet exhaustive, but is a good start from @estebank and @nikomatsakis :

* [ ] developing libraries for use in many different environments
* [ ] targeting embedded systems or those with very narrow requirements
* [ ] maintaining systems into production
* [ ] configuring and tuning systems for high performance
* [ ] combining parallel processing of data with I/O
* [ ] missing cool features from other languages that maybe Rust should have (JS, C#, Clojure, Kotlin, whatever)
* [ ] learning async Rust when you already know Rust
* [ ] learning async Rust when you don't already know Rust
* [ ] onboarding new employees into a system built using async Rust
* [ ] integrating with other async runtimes, esp. in other languages
* [ ] supporting systems that integrate multiple reactors
* [ ] migrating an existing sync crate to async
* [ ] supporting both sync and async apis in the same crate

(I will expand this issue body with xrefs to other issues, PRs, and stories, but I won't get to that until tonight or tomorrow)
